### Основы NumPy

1) Импортировать NumPy под именем np

In [3]:
import numpy as np

2) Напечатать версию и конфигурацию

In [4]:
print(np.__version__)
np.show_config()

1.18.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3) Создать вектор (одномерный массив) размера 10, заполненный нулями

In [5]:
vec = np.zeros(10, dtype=int)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


4) Создать вектор размера 10, заполненный единицами

In [6]:
vec = np.ones(10, dtype=int)
print(vec)

[1 1 1 1 1 1 1 1 1 1]


5) Создать вектор размера 10, заполненный числом 2.5

In [7]:
vec = np.full(10, 2.5)
print(vec)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
vec = np.zeros(10, dtype=int)
vec[4] = 1
print(vec)

[0 0 0 0 1 0 0 0 0 0]


7) Создать вектор со значениями от 10 до 49

In [9]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8) Развернуть вектор (первый становится последним)

In [10]:
vec = np.arange(11)
vec = vec[::-1]
print(vec)

[10  9  8  7  6  5  4  3  2  1  0]


9) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [11]:
matr = np.arange(9).reshape(3,3)
print(matr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10) Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
vec = [1,2,0,0,4,0]
nz = np.nonzero(vec)
print(nz)

(array([0, 1, 4]),)


11) Создать 3x3 единичную матрицу

In [13]:
e = np.eye(3, dtype=int)
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12) Создать массив 3x3x3 со случайными значениями

In [14]:
matr = np.random.random((3,3,3))
print(matr)

[[[0.62291762 0.88565533 0.13584359]
  [0.09114074 0.36485188 0.62492714]
  [0.18157686 0.80476566 0.16489944]]

 [[0.07176109 0.05719744 0.8187876 ]
  [0.49894812 0.20249786 0.49236763]
  [0.63673861 0.73893059 0.50010186]]

 [[0.15484744 0.62862263 0.55780909]
  [0.5704026  0.84836307 0.60232804]
  [0.42337532 0.34225373 0.24010255]]]


13) Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [15]:
matr = np.random.random((10,10))
print(matr.min())
print(matr.max())

0.0016678753020176185
0.9814902784458359


14) Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [16]:
vec = np.random.random(30)
print(vec.mean())

0.5154345680657647


15) Создать матрицу с 0 внутри, и 1 на границах

In [17]:
vec = np.ones((5,5), dtype=int)
vec[1:-1,1:-1] = 0
print(vec)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16) Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [18]:
matr = np.diag(np.arange(0, 5))
print(matr)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


17) Создать 8x8 матрицу и заполнить её в шахматном порядке

In [19]:
vec = np.zeros((8,8), dtype=int)
vec[1::2,::2] = 1
vec[::2,1::2] = 1
print(vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18) Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [20]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


19) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [21]:
matr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20) Перемножить матрицы 5x3 и 3x2

In [22]:
matr = np.dot(np.ones((5,3), dtype=int), np.ones((3,2), dtype=int))
print(matr)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


21) Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [23]:
vec = np.arange(11)
vec[(3 < vec) & (vec < 8)] *= -1
print(vec)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


22) Создать 5x5 матрицу со значениями в строках от 0 до 4

In [24]:
matr = np.zeros((5,5), dtype=int)
matr += np.arange(5)
print(matr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


23) Есть генератор, сделать с его помощью массив

In [25]:
def generator():
    for el in range(20):
        yield el

vec = np.fromiter(generator(), dtype=int)
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


24) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [26]:
vec = np.random.random(12)
vec.sort()
print(vec[1:-1])

[0.197846   0.20208845 0.46654037 0.48289103 0.50179173 0.65206402
 0.6521073  0.65359579 0.66738243 0.78945613]


25) Отсортировать вектор

In [27]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


26) Проверить, одинаковы ли 2 numpy массива

In [28]:
a = np.random.randint(0, 50, 20)
b = np.random.randint(0, 50, 20)
print(a)
print(b)
print(np.allclose(a,b))

[36  6  1 37 20 27 31 46 30 18 12 25 28 28 18 34 30  0 44  7]
[14  0 20 35  0 32 33 16  0 13 36 49 21  1  7 46 40 30 20 28]
False


27) Сделать массив неизменяемым

In [29]:
vec.flags.writeable = False

28) Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [30]:
matr = np.random.random((10, 2))
x = matr[:,0]
y = matr[:,1]
r = np.hypot(x, y)
t = np.arctan2(y, x)
print(r, t)

[1.18117889 0.73762129 0.61680346 0.97690744 1.02165837 1.11343146
 0.95941907 1.09715053 0.44726638 1.09557553] [0.89315293 1.48206807 1.55171545 1.03345761 0.23751315 0.45933033
 0.34430154 0.6049445  1.36690146 0.60250809]


29) Заменить максимальный элемент на ноль

In [31]:
vec = np.random.randint(0, 50, 10)
print(vec, vec.max())
vec[vec.argmax()] = 0
print(vec)

[12 36 35 34 18  1 48 45  4 45] 48
[12 36 35 34 18  1  0 45  4 45]


30) Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [32]:
vec = np.zeros((5, 5), [('x', float), ('y', float)])
vec['x'] = np.meshgrid(np.linspace(0, 1, 5))
vec['y'] = np.meshgrid(np.linspace(0, 1, 5))
print(vec)

[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


31) Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [33]:
print('Integers:')
for tp in [np.int8, np.int32, np.int64]:
    print(tp, np.iinfo(tp).min, np.iinfo(tp).max)
print('Floats:')
for tp in [np.float32, np.float64]:
    print(tp, np.finfo(tp).eps, np.finfo(tp).min, np.finfo(tp).max)

Integers:
<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
Floats:
<class 'numpy.float32'> 1.1920929e-07 -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> 2.220446049250313e-16 -1.7976931348623157e+308 1.7976931348623157e+308


32) Напечатать все значения в массиве

In [34]:
vec = np.random.randint(0, 20, 10)
print(vec)

[15 19 12  6 11  7  0  3 15  0]


33) Найти ближайшее к заданному значению число в заданном массиве

In [35]:
vec = np.arange(50)
nbr = np.random.uniform(0, 50)
print(nbr)
print(vec[(np.abs(vec - nbr)).argmin()])

0.15309701185506897
0


34) Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [36]:
vec = np.zeros((3, 3), [('position', [('x', int), ('y', int)]),
                        ('color',    [('r', int), ('g', int), ('b', int)])])
print(vec)

[[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]
 [((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]
 [((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]]


35) Дан массив (10, 2) координат, найти расстояние от каждой точки до каждой

In [37]:
import scipy.spatial as sp
matr = np.random.random((10, 2))
dist = sp.distance.cdist(matr, matr)
print(matr)
print(dist)

[[0.42103398 0.96271374]
 [0.23885149 0.3704902 ]
 [0.18796371 0.08543852]
 [0.20675631 0.02483949]
 [0.63159364 0.98003347]
 [0.76516043 0.6522104 ]
 [0.86579624 0.27335353]
 [0.90561504 0.34842592]
 [0.24812058 0.22775372]
 [0.18532095 0.43321346]]
[[0.         0.61961212 0.90770786 0.96204108 0.21127078 0.46350333
  0.82038465 0.78241187 0.75502667 0.5795957 ]
 [0.61961212 0.         0.28955833 0.3471376  0.72511337 0.59696513
  0.63442513 0.66712852 0.14303712 0.08246046]
 [0.90770786 0.28955833 0.         0.06344607 0.99855277 0.80894154
  0.70339817 0.76432049 0.15450717 0.34778498]
 [0.96204108 0.3471376  0.06344607 0.         1.04541011 0.83988655
  0.7043386  0.77013747 0.20708739 0.40893615]
 [0.21127078 0.72511337 0.99855277 1.04541011 0.         0.35398878
  0.74447794 0.68848807 0.84437931 0.70581261]
 [0.46350333 0.59696513 0.80894154 0.83988655 0.35398878 0.
  0.39199502 0.3346827  0.66894968 0.6198173 ]
 [0.82038465 0.63442513 0.70339817 0.7043386  0.74447794 0.39199502

36) Преобразовать массив из float в int

In [38]:
vec = np.random.random(10) * 10
print(vec)
vec = vec.astype(np.int, copy=False)
print(vec)

[5.10698097 5.7753419  9.86239378 5.12026228 1.37902454 8.72208013
 9.2228197  6.25936901 6.79928278 1.58815326]
[5 5 9 5 1 8 9 6 6 1]


37) Отнять среднее из каждой строки в матрице

In [39]:
matr = np.random.rand(5, 5)
print(matr)
res = matr - matr.mean(axis=1, keepdims=True)
print(res)

[[0.26023853 0.92586424 0.91219575 0.61706651 0.09561146]
 [0.14124254 0.68473    0.13131879 0.41156207 0.83171018]
 [0.16054078 0.66657634 0.95352565 0.42125543 0.58203731]
 [0.14120247 0.97460066 0.60862899 0.82438828 0.71092703]
 [0.67497826 0.98724617 0.10385965 0.51784023 0.66670003]]
[[-0.30195677  0.36366894  0.35000045  0.05487121 -0.46658384]
 [-0.29887018  0.24461728 -0.30879393 -0.02855065  0.39159747]
 [-0.39624632  0.10978924  0.39673854 -0.13553167  0.02525021]
 [-0.51074701  0.32265118 -0.04332049  0.17243879  0.05897754]
 [ 0.08485339  0.3971213  -0.48626522 -0.07228464  0.07657516]]


38) Отсортировать матрицу по n-ому столбцу

In [40]:
matr = np.random.randint(0, 10, (5, 5))
n = 0
print(matr[matr[:, n].argsort()])

[[1 7 9 5 4]
 [1 1 1 0 4]
 [2 0 7 4 5]
 [3 3 8 8 7]
 [7 3 9 8 0]]


39) Определить, есть ли в 2D массиве нулевые столбцы

In [41]:
matr = np.random.randint(0, 1, (10, 10))
print((~matr.any(axis=0)).any())

True


40) Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [42]:
vec = np.ones(10, dtype=int)
ind = np.random.randint(0, len(vec), 10)
vec += np.bincount(ind, minlength=len(vec))
print(vec)

[3 1 1 2 2 2 3 2 2 2]


41) Найти диагональные элементы произведения матриц

In [43]:
a = np.random.randint(0, 10, (5, 5))
b = np.random.randint(0, 10, (5, 5))
print(np.diag(np.dot(a, b)))

[118 159  48  80 169]


42) Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [44]:
vec = np.arange(1, 6)
res = np.zeros(len(vec) + (len(vec) - 1) * 3, dtype=int)
res[::4] = vec
print(res)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


43) Поменять 2 строки в матрице

In [45]:
matr = np.random.randint(0, 10, (5, 5))
print(matr)
matr[[0,1]] = matr[[1,0]]
print(matr)

[[1 1 1 6 8]
 [3 0 8 8 6]
 [0 4 0 7 6]
 [7 6 3 2 3]
 [1 6 5 0 1]]
[[3 0 8 8 6]
 [1 1 1 6 8]
 [0 4 0 7 6]
 [7 6 3 2 3]
 [1 6 5 0 1]]
