### Основы NumPy

1) Импортировать NumPy под именем np

In [146]:
import numpy as np

2) Напечатать версию и конфигурацию

In [147]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3) Создать вектор (одномерный массив) размера 10, заполненный нулями

In [148]:
vec = np.zeros(10, dtype=int)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


4) Создать вектор размера 10, заполненный единицами

In [149]:
vec = np.ones(10, dtype=int)
print(vec)

[1 1 1 1 1 1 1 1 1 1]


5) Создать вектор размера 10, заполненный числом 2.5

In [150]:
vec = np.full(10, 2.5)
print(vec)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [151]:
vec = np.zeros(10, dtype=int)
vec[4] = 1
print(vec)

[0 0 0 0 1 0 0 0 0 0]


7) Создать вектор со значениями от 10 до 49

In [152]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8) Развернуть вектор (первый становится последним)

In [153]:
vec = np.arange(11)
vec = vec[::-1]
print(vec)

[10  9  8  7  6  5  4  3  2  1  0]


9) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [154]:
matr = np.arange(9).reshape(3,3)
print(matr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10) Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [155]:
vec = [1,2,0,0,4,0]
nz = np.nonzero(vec)
print(nz)

(array([0, 1, 4]),)


11) Создать 3x3 единичную матрицу

In [156]:
e = np.eye(3, dtype=int)
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12) Создать массив 3x3x3 со случайными значениями

In [157]:
matr = np.random.random((3,3,3))
print(matr)

[[[0.30001756 0.23771122 0.13275683]
  [0.68661347 0.99379573 0.17177489]
  [0.2899795  0.33674426 0.54504124]]

 [[0.84610252 0.57297988 0.86600982]
  [0.28465168 0.00794669 0.20507107]
  [0.54686046 0.68106174 0.22251276]]

 [[0.41441065 0.0777052  0.27243512]
  [0.2247652  0.76179759 0.37304041]
  [0.43377422 0.08664915 0.51475297]]]


13) Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [158]:
matr = np.random.random((10,10))
print(matr.min())
print(matr.max())

0.03781416251265657
0.9993211487554221


14) Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [159]:
vec = np.random.random(30)
print(vec.mean())

0.43554129897925414


15) Создать матрицу с 0 внутри, и 1 на границах

In [160]:
vec = np.ones((5,5), dtype=int)
vec[1:-1,1:-1] = 0
print(vec)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16) Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [161]:
matr = np.diag(np.arange(0, 5))
print(matr)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


17) Создать 8x8 матрицу и заполнить её в шахматном порядке

In [162]:
vec = np.zeros((8,8), dtype=int)
vec[1::2,::2] = 1
vec[::2,1::2] = 1
print(vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


18) Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [163]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


19) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [164]:
matr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20) Перемножить матрицы 5x3 и 3x2

In [165]:
matr = np.dot(np.ones((5,3), dtype=int), np.ones((3,2), dtype=int))
print(matr)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


21) Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [166]:
vec = np.arange(11)
vec[(3 < vec) & (vec < 8)] *= -1
print(vec)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


22) Создать 5x5 матрицу со значениями в строках от 0 до 4

In [167]:
matr = np.zeros((5,5), dtype=int)
matr += np.arange(5)
print(matr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


23) Есть генератор, сделать с его помощью массив

In [168]:
def generator():
    for el in range(20):
        yield el

vec = np.fromiter(generator(), dtype=int)
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


24) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [169]:
vec = np.random.random(12)
vec.sort()
print(vec[1:-1])

[0.42547347 0.48867581 0.58791346 0.59764546 0.61842149 0.63052563
 0.68999089 0.73124546 0.85487987 0.96385135]


25) Отсортировать вектор

In [170]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


26) Проверить, одинаковы ли 2 numpy массива

In [171]:
a = np.random.randint(0, 50, 20)
b = np.random.randint(0, 50, 20)
print(a)
print(b)
print(np.allclose(a,b))

[14 39  1 34 31 27  8  5 49 28 25 42  8 10 15 46  4  7 41 25]
[33 48  4  3 49 26 19 22 39 40 39 47  5 41  5 41 16 25 18 19]
False


27) Сделать массив неизменяемым

In [172]:
vec.flags.writeable = False

28) Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [173]:
matr = np.random.random((10, 2))
x = matr[:,0]
y = matr[:,1]
r = np.hypot(x, y)
t = np.arctan2(y, x)
print(r, t)

[1.10301068 1.09227574 0.97760689 0.75633132 0.65742965 1.27276448
 0.95279067 0.89226599 0.52942602 0.78755322] [0.69341557 0.81021191 0.54388172 0.89740143 1.09255024 0.7001718
 1.18310303 0.57059798 0.15903718 1.53578779]


29) Заменить максимальный элемент на ноль

In [174]:
vec = np.random.randint(0, 50, 10)
print(vec, vec.max())
vec[vec.argmax()] = 0
print(vec)

[19 26 26 26 46 22  8 31 38 16] 46
[19 26 26 26  0 22  8 31 38 16]


30) Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [175]:
vec = np.zeros((5, 5), [('x', float), ('y', float)])
vec['x'] = np.meshgrid(np.linspace(0, 1, 5))
vec['y'] = np.meshgrid(np.linspace(0, 1, 5))
print(vec)

[[(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]
 [(0.  , 0.  ) (0.25, 0.25) (0.5 , 0.5 ) (0.75, 0.75) (1.  , 1.  )]]


31) Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [176]:
print('Integers:')
for tp in [np.int8, np.int32, np.int64]:
    print(tp, np.iinfo(tp).min, np.iinfo(tp).max)
print('Floats:')
for tp in [np.float32, np.float64]:
    print(tp, np.finfo(tp).eps, np.finfo(tp).min, np.finfo(tp).max)

Integers:
<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
Floats:
<class 'numpy.float32'> 1.1920929e-07 -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> 2.220446049250313e-16 -1.7976931348623157e+308 1.7976931348623157e+308


32) Напечатать все значения в массиве

In [177]:
vec = np.random.randint(0, 20, 10)
print(vec)

[12 14  5 18  7 16  3 10  7  6]


33) Найти ближайшее к заданному значению число в заданном массиве

In [178]:
vec = np.arange(50)
nbr = np.random.uniform(0, 50)
print(nbr)
print(vec[(np.abs(vec - nbr)).argmin()])

13.713324237058078
14


34) Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [179]:
vec = np.zeros((3, 3), [('position', [('x', int), ('y', int)]),
                        ('color',    [('r', int), ('g', int), ('b', int)])])
print(vec)

[[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]
 [((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]
 [((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))]]


35) Дан массив (10, 2) координат, найти расстояние от каждой точки до каждой

In [180]:
import scipy.spatial as sp
matr = np.random.random((10, 2))
dist = sp.distance.cdist(matr, matr)
print(matr)
print(dist)

[[0.82129274 0.33462545]
 [0.85991606 0.18393184]
 [0.13404753 0.45617312]
 [0.25002087 0.83834122]
 [0.85743851 0.38849466]
 [0.6629964  0.30270977]
 [0.81223372 0.36947242]
 [0.02783706 0.53193877]
 [0.43578926 0.36542371]
 [0.21967897 0.56556027]]
[[0.         0.15556453 0.69791103 0.76163056 0.06487225 0.16148171
  0.03600523 0.81762122 0.38673177 0.64441448]
 [0.15556453 0.         0.77524217 0.89455227 0.20457782 0.22996859
  0.19156959 0.90192255 0.46132725 0.74534809]
 [0.69791103 0.77524217 0.         0.39937736 0.72654999 0.5507612
  0.68370572 0.13046493 0.31509289 0.13891829]
 [0.76163056 0.89455227 0.39937736 0.         0.75585588 0.67635037
  0.73206642 0.37848132 0.50809533 0.27446326]
 [0.06487225 0.20457782 0.72654999 0.75585588 0.         0.21252478
  0.04904405 0.84191139 0.42227995 0.66188327]
 [0.16148171 0.22996859 0.5507612  0.67635037 0.21252478 0.
  0.16349015 0.67525796 0.23570345 0.51538405]
 [0.03600523 0.19156959 0.68370572 0.73206642 0.04904405 0.16349015


36) Преобразовать массив из float в int

In [181]:
vec = np.random.random(10) * 10
print(vec)
vec = vec.astype(np.int, copy=False)
print(vec)

[3.96002675 2.0998832  8.87069177 5.37232065 0.4246939  4.04711917
 5.39895128 5.24137972 5.74991842 9.28878536]
[3 2 8 5 0 4 5 5 5 9]


37) Отнять среднее из каждой строки в матрице

In [182]:
matr = np.random.rand(5, 5)
print(matr)
res = matr - matr.mean(axis=1, keepdims=True)
print(res)

[[0.73337524 0.0060671  0.08987068 0.59550841 0.98583343]
 [0.73291149 0.16124191 0.85872879 0.85418181 0.38548948]
 [0.7190278  0.00806301 0.87599568 0.47080526 0.83623521]
 [0.03180311 0.20668938 0.54691064 0.08393295 0.42030057]
 [0.59631991 0.54578316 0.60993184 0.55260859 0.91299745]]
[[ 0.25124427 -0.47606387 -0.39226029  0.11337744  0.50370246]
 [ 0.1344008  -0.43726879  0.26021809  0.25567111 -0.21302121]
 [ 0.13700241 -0.57396238  0.29397029 -0.11122013  0.25420982]
 [-0.22612422 -0.05123795  0.28898331 -0.17399438  0.16237324]
 [-0.04720828 -0.09774503 -0.03359635 -0.0909196   0.26946926]]


38) Отсортировать матрицу по n-ому столбцу

In [184]:
matr = np.random.randint(0, 10, (5, 5))
n = 0
print(matr[matr[:, n].argsort()])

[[3 4 8 5 1]
 [3 3 3 3 5]
 [6 0 2 3 7]
 [7 1 9 7 9]
 [9 6 8 9 2]]


39) Определить, есть ли в 2D массиве нулевые столбцы

In [185]:
matr = np.random.randint(0, 1, (10, 10))
print((~matr.any(axis=0)).any())

True


40) Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [186]:
vec = np.ones(10, dtype=int)
ind = np.random.randint(0, len(vec), 10)
vec += np.bincount(ind, minlength=len(vec))
print(vec)

[1 2 2 2 2 3 3 1 1 3]


41) Найти диагональные элементы произведения матриц

In [187]:
a = np.random.randint(0, 10, (5, 5))
b = np.random.randint(0, 10, (5, 5))
print(np.diag(np.dot(a, b)))

[196 110 133  79  51]


42) Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [188]:
vec = np.arange(1, 6)
res = np.zeros(len(vec) + (len(vec) - 1) * 3, dtype=int)
res[::4] = vec
print(res)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


43) Поменять 2 строки в матрице

In [193]:
matr = np.random.randint(0, 10, (5, 5))
print(matr)
matr[[0,1]] = matr[[1,0]]
print(matr)

[[7 9 3 9 8]
 [8 3 2 9 1]
 [6 1 5 1 9]
 [0 4 1 6 7]
 [4 4 2 2 1]]
[[8 3 2 9 1]
 [7 9 3 9 8]
 [6 1 5 1 9]
 [0 4 1 6 7]
 [4 4 2 2 1]]
